version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres-user
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=userdb
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres-user
      - kafka
    networks:
      - ecommerce-network
    restart: on-failure

  product-catalog-service:
    build: ./product-catalog-service
    ports:
      - "8082:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/productdb
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - mongodb
      - kafka
    networks:
      - ecommerce-network
    restart: on-failure

  shopping-cart-service:
    build: ./shopping-cart-service
    ports:
      - "8083:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - redis
      - kafka
    networks:
      - ecommerce-network
    restart: on-failure

  order-service:
    build: ./order-service
    ports:
      - "8084:8080"
    environment:
      - DB_HOST=postgres-order
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=orderdb
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres-order
      - kafka
      - product-catalog-service
      - shopping-cart-service
      - user-service
    networks:
      - ecommerce-network
    restart: on-failure

  payment-service:
    build: ./payment-service
    ports:
      - "8085:8080"
    environment:
      - DB_HOST=postgres-payment
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=paymentdb
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres-payment
      - kafka
      - order-service
    networks:
      - ecommerce-network
    restart: on-failure

  notification-service:
    build: ./notification-service
    ports:
      - "8086:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USERNAME=notification
      - SMTP_PASSWORD=password
    depends_on:
      - kafka
    networks:
      - ecommerce-network
    restart: on-failure

  postgres-user:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userdb
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  postgres-order:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orderdb
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  postgres-payment:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=paymentdb
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  mongodb:
    image: mongo:5
    volumes:
      - mongodb-data:/data/db
    networks:
      - ecommerce-network

  redis:
    image: redis:6
    volumes:
      - redis-data:/data
    networks:
      - ecommerce-network

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - ecommerce-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres-user-data:
  postgres-order-data:
  postgres-payment-data:
  mongodb-data:
  redis-data:
  zookeeper-data: