apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: voloshmiak/ecommerce-project:notification-service-v1.0
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: NOTIFICATION_KAFKA_HOST
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: NOTIFICATION_KAFKA_PORT
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SENDGRID_API_KEY
