apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: voloshmiak/ecommerce-project:payment-service-v1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom: { configMapKeyRef: { name: service-config, key: PAYMENT_DB_HOST } }
            - name: DB_PORT
              valueFrom: { configMapKeyRef: { name: service-config, key: PAYMENT_DB_PORT } }
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: service-secrets, key: POSTGRES_PAYMENT_PASSWORD } }
            - name: DB_NAME
              valueFrom: { configMapKeyRef: { name: service-config, key: PAYMENT_DB_NAME } }
            - name: SERVER_PORT
              valueFrom: { configMapKeyRef: { name: service-config, key: PAYMENT_SERVER_PORT } }
            - name: CART_HOST
              valueFrom: { configMapKeyRef: { name: service-config, key: PAYMENT_CART_HOST } }
            - name: CART_PORT
              valueFrom: { configMapKeyRef: { name: service-config, key: PAYMENT_CART_PORT } }
            - name: KAFKA_HOST
              valueFrom: { configMapKeyRef: { name: service-config, key: PAYMENT_KAFKA_HOST } }
            - name: KAFKA_PORT
              valueFrom: { configMapKeyRef: { name: service-config, key: PAYMENT_KAFKA_PORT } }
            - name: STRIPE_SECRET
              valueFrom: { secretKeyRef: { name: service-secrets, key: STRIPE_SECRET } }
            - name: DB_MIGRATIONS_PATH
              value: "/root/migrations"