apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-secret
  namespace: data
type: Opaque
stringData:
  # Змінні, які очікує образ postgres
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "userdb"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user-service
  namespace: data
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-user
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-user
  namespace: data
spec:
  serviceName: "postgres-user-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-user-secret
          volumeMounts:
            - name: postgres-user-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-user-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi # Виділяємо 2GB для бази даних користувачів